[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Julien Girard <julien.girard2@cea.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
nom = "6.0"
dot = "0.1.4"
